package com.example.preguntas1.Preguntas

import android.os.Bundle
import android.util.TypedValue
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.cardview.widget.CardView
import androidx.core.content.ContextCompat
import com.example.preguntas1.Menu.MenuActivity.Companion.DEEP_KEY
import com.example.preguntas1.Menu.MenuActivity.Companion.MET_KEY
import com.example.preguntas1.Menu.MenuActivity.Companion.TYPE_KEY
import com.example.preguntas1.Menu.MenuActivity.Companion.WHO_KEY
import com.example.preguntas1.Menu.MenuActivity.Companion.RANDOM_KEY
import com.example.preguntas1.Menu.MenuActivity.Companion.LINES_KEY
import com.example.preguntas1.R
import kotlin.random.Random

class PreguntasActivity : AppCompatActivity() {

    private lateinit var tvQuestion: TextView
    private lateinit var cvQuestion: CardView
    private lateinit var tvtitleQuestion: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_preguntas)
        val deepQuestions: List<String> = listOf(
            "¿Eres más mental o emocional?",
            "¿Eres más mental o emocional?",
            "¿Te resulta fácil aceptar ayuda para lograr tus sueños?",
            "¿Te arrepientes de no haber hecho algo en la vida?",
            "¿Qué es lo que te pone más nervioso?",
            "¿Cómo es la relación con tus padres?",
            "¿Te castigaban mucho cuando eras pequeño?",
            "¿Cuál ha sido la mejor época de tu vida? ¿Y la peor?",
            "¿Qué pesadillas te han provocado sudores más fríos?",
            "¿Cómo te describirías a ti mismo?",
            "¿Qué es lo que más valoras en una amistad?",
            "¿Cuándo fue la última vez que lloraste delante de otra persona?",
            "¿Qué significa para ti nuestra amistad?",
            "¿Cómo te gusta ser reconfortado o animado cuando estás triste o enfadado?",
            "¿Cuál es el momento de tu vida que más te puso a prueba?",
            "¿Te arrepientes de algo? Si es así, ¿de qué?",
            "Si tuvieras todo el valor posible para hacer aquello que más te asusta, ¿qué harías?",
            "¿Qué pensamientos te dificultan dormir por las noches?",
            "¿Qué es lo que más te estresa en la vida?",
            "¿Cuál es la peor decisión que has cometido?",
            "¿Cuál fue tu primera amistad? ¿Sigue en tu vida?",
            "¿Qué objeto tiene para ti mayor valor sentimental?",
            "¿Cómo puedo ser un mejor amigo para ti?",
            "Si pudieras cambiar una sola cosa sobre ti, ¿cuál sería?",
            "¿Qué es lo que más te hace llorar?",
            "¿Tienes alguna manía extraña que no conozco?",
            "¿Quién es la persona más importante de tu vida?",
            "¿Qué fue lo primero que pensaste de mí nada más conocernos?",
            "¿Qué es lo que realmente te saca de tus casillas?",
            "¿Te resulta fácil confiar en alguien?",
            "¿Podrías perdonar a alguien que te ha sido infiel si te enteraras que de todas maneras te ama?",
            "¿Qué persona ha ejercido una influencia decisiva en ti?",
            "¿Qué es lo que más te gusta de mí?",
            "¿Qué es aquello que me hace diferente del resto de personas?",
            "¿Cuándo fue la última vez que te pusiste triste?",
            "¿Por qué acabó tu última relación?",
            "¿Que te hace sentir culpa?",
            "¿Qué cualidades valoras más en alguien?",
            "¿Cómo me describirías?",
            "¿Hay algo que pienses que los demás piensan de ti y no es cierto?",
            "¿Qué cuatro adjetivos te dicen cómo eres?",
            "¿Qué es lo que más te gusta sobre tu persona?",
            "¿Qué es lo que te ha decepcionado más en una amistad?",
            "¿De qué estás más orgulloso en esta vida?",
            "¿De que te arrepientes?",
            "¿Cómo lidias con la ansiedad?",
            "¿Cómo lidias con el estres?",
            "¿Con qué tipo de personas sientes más inseguridad o timidez?",
            "¿Contratarías a un amigo en tu empresa?",
            "¿Preferirías tener un gran talento innato para una actividad, o la capacidad para poder esforzarte mucho?",
            "¿Cuál es tu principal miedo irracional?",
            "Del 1 al 100 que tan estresado/a te sentis",
            "Del 1 al 100 en que nivel esta tu autoestima",
            "Del 1 al 100 cuanta ansiedad consideras tener actualmente",
            "Del 1 al 100 que tanto confias en vos mismo/a",
            "¿A qué le tiene más miedo?",
            "¿Cuáles son tus mayores prioridades en la vida?",
            "¿A quién te pareces más en tu familia?",
            "¿Cómo te enfrentas a los disgustos?",
            "¿Qué es lo que más te apetece hacer cada día?",
            "¿Cuál ha sido tu momento de mayor orgullo?",
            "¿Has perdido a alguien cercano?",
            "¿Eres espiritual?",
            "¿Crees que eres honesto contigo mismo?",
            "¿Quién narraría un audiolibro sobre tu vida?",
            "Si pudieras cambiar algo de tu vida inmediatamente, ¿qué sería?",
            "¿Cuál es tu mayor habilidad?",
            "¿Qué afición siempre has querido practicar?",
            "¿Cómo esperas que te perciba la gente?",
            "¿Qué es lo que más te alegra?",
            "¿Ha perdido alguna vez a un mejor amigo?",
            "¿Qué es lo que te hace sentir más visto?",
            "¿Crees que guardar secretos es malo?",
            "¿Cuándo te sientes más libre?",
            "¿Crees que es bueno guardar rencor?",
            "¿Qué es lo más loco que has hecho por otra persona y por qué lo hiciste?",
            "¿Eres pesimista u optimista?",
            "¿Cuándo fue la última vez que lloraste?",
            "¿Cuál es el lugar más impresionante que has visitado en persona?",
            "¿Qué crees que la gente asume automáticamente cuando te conoce por primera vez?",
            "¿Qué desearías saber cuando eras más joven?",
            "¿Cuál es la mejor mala decisión que has tomado en tu vida?",
            "¿Qué intentarías si supiera que no va a fracasar?",
            "¿Cuándo fue la última vez que intentaste algo nuevo?",
            "¿Con quién te comparas más?",
            "¿Hay alguna lección importante que hayas aprendido por las malas?",
            "¿A qué desearías dedicar más tiempo?",
            "¿Hay algo en lo que sabes que te equivocas?",
            "¿Cuál es tu mayor creencia ciega?",
            "¿Cuál ha sido el momento más decisivo de tu vida hasta ahora?",
            "¿Alguna vez se ha hecho realidad tu miedo más profundo?",
            "¿Merece todo el mundo una segunda oportunidad?",
            "¿Cuál es el encuentro más extraño que has tenido?",
            "¿Qué es lo que te hace sentir más vivo?",
            "¿Cuándo fue la última vez que te sentiste perdido?",
            "¿Qué es lo que más te gusta de ti mismo?",
            "¿Cuál es la pregunta que más miedo te da?",
            "¿Qué es lo que más te gusta de tu personalidad?",
            "¿Qué has hecho como adulto de lo que tu yo más joven estaría orgulloso?",
            "Cuéntame un día en que fuiste feliz",
            "¿A qué lugar te gustaría volver a viajar?",
            "¿Qué te pone la piel de gallina?",
            "¿Cuál es tu lenguaje del amor?",
            "¿Cuál es la forma de expresión personal que no te has atrevido a explorar?",
            "¿Qué recuerdo te hace sonreír instantáneamente?",
            "¿De qué cosa crees que sentirás nostalgia dentro de 30 años?",
            "¿Tienes algún recuerdo de tu infancia que siempre estará contigo?",
            "¿Cómo te sientes mejor apoyado en los momentos difíciles?",
            "¿Qué te gustaría que la gente entendiera mejor de ti?",
            "¿Qué es lo que más te gusta de nuestra amistad? ¿Qué te gustaría mejorar?",
            "¿Cuál es el recuerdo favorito que tienes de nosotros juntos?",
            "¿Te recargas estando rodeado de otras personas o pasando tiempo a solas?"
        )
        val whoIsQuestions: List<String> = listOf(
            "¿Quién es más probable que atienda tu llamada a media noche?",
            "¿Quién es más probable que se sienta como en casa en tu casa?",
            "¿Quién se llevaría bien con los padres de todos?",
            "¿Quién es más probable que le organice una fiesta sorpresa a alguien?",
            "¿Quién tiene más probabilidades de ser un gran chófer profesional?",
            "¿Quién es más probable que haga a mano tu regalo de cumpleaños?",
            "¿Quién es más probable que haga reír a alguien cuando se siente triste?",
            "¿Quién es más probable que te haga una torta por tu cumpleaños?",
            "¿A quién es más probable que se le ocurra apodos para todos?",
            "¿Quién es más probable que responda un mensaje de texto o correo electrónico de inmediato?",
            "¿Quién es más probable que te preste su libro favorito?",
            "¿Quién es más probable que se olvide de devolver un libro que pidió prestado?",
            "¿Quién es más probable que se quede despierto toda la noche mirando su teléfono?",
            "¿Quién es más probable que sepa todos los chismes de la oficina?",
            "¿Quién tiene más probabilidades de quedarse dormido durante una reunión?",
            "¿Quién es más probable que guarde un secreto importante?",
            "¿Quién tiene más probabilidades de olvidarse un cumpleaños?",
            "¿Quién es más probable que gaste todo su sueldo en ropa o zapatos?",
            "¿Quién es más probable que deje caer su teléfono nuevo y lo rompa?",
            "¿Quién es más probable que olvide la bolsa de almuerzo que empacó?",
            "¿Quién es más probable que pierda un vuelo?",
            "¿Quién tiene más probabilidades de dar el mejor regalo del Amigo Invisible?",
            "¿Quién es más probable que tenga a su mascota en su regazo durante una reunión o llamada?",
            "¿Quién es más probable que se olvide de silenciar su micrófono durante una reunión o conferencia telefónica?",
            "¿Quién es más probable que diga algo importante mientras está silenciado en una llamada?",
            "¿Quién tiene más probabilidades de tener 20 pestañas abiertas en su escritorio?",
            "¿Quién tiene más probabilidades de hacer trampa en un juego de mesa?",
            "¿Quién tiene más probabilidades de presionar 5 veces el botón de posponer en el despertador?",
            "¿Quién es más probable que duerma mientras suena la alarma?",
            "¿Quién es más probable que pase horas leyendo chismes de celebridades?",
            "¿Quién es más probable que te anime en un día difícil?",
            "¿Quién está más dispuesto a ayudar a resolver un problema?",
            "¿Quién es más probable que te haga olvidar tus problemas por un tiempo?",
            "¿Quién es más probable que tenga un oído disponible para escuchar?",
            "¿Quién tiene más probabilidades de convertirse en un gran líder en el futuro?",
            "¿Quién tiene más probabilidades de salvar el día cuando las cosas salen mal?",
            "¿Quién es más probable que diga cosas buenas de ti a tus espaldas?",
            "¿Quién es más probable que te inspire?",
            "¿Quién tiene más probabilidades de sacar lo mejor de las personas que conoce?",
            "¿Quién tiene más probabilidades de tener un impacto en la historia?",
            "¿Quién es más probable que ofrezca apoyo moral a un amigo?",
            "¿Quién es más probable que te dé el regalo perfecto?",
            "¿Quién es más probable que ayude a un extraño?",
            "¿Quién es más probable que realice un acto de bondad al azar?",
            "¿Quién tiene más probabilidades de hacer nuevos amigos en un lugar nuevo?",
            "¿Quién tiene más probabilidades de entrenar a otros de alguna manera?",
            "¿Quién es más probable que coma pizza fría?",
            "¿Quién es más probable que coma desayuno en la cena?",
            "¿Quién es más propenso a olvidarse la billetera cuando sale a comer?",
            "¿Quién es más probable que hable en una sala de cine durante una función?",
            "¿Quién es más probable que regañe a otros por hablar en una sala de cine durante una función?",
            "¿Quién tiene más probabilidades de completar un desafío en público que conduzca a un arresto?",
            "¿Quién es más probable que use todas las mantas cuando duerme?",
            "¿Quién es más probable que sea el planificador de viajes para las vacaciones de sus familiares o amigos?",
            "¿Quién tiene más probabilidades de ver un programa completo en un solo día?",
            "¿Quién es más probable que se olvide de comprar alimentos para la semana?",
            "¿Quién es más probable que se coma todo el pochoclo durante una película?",
            "¿Quién es más probable que grite pidiendo ayuda cuando ve una araña?",
            "¿Quién tiene más probabilidades de matar una araña cuando la ve?",
            "¿Quién es más probable que se mude a una cabaña en el bosque?",
            "¿Quién es más probable que haga voces distintas para los personajes cuando lee un libro en voz alta?",
            "¿Quién tiene más probabilidades de hacerse un tatuaje vergonzoso?",
            "¿Quién tiene más probabilidades de copiar en un examen?",
            "¿Quién tiene más probabilidades de orinarse en la ducha?",
            "¿Quién tiene más probabilidades de no cambiar nunca las sábanas?",
            "¿Quién tiene más probabilidades de llegar tarde?",
            "¿Quién suele faltar a clase?",
            "¿Quién tiene más probabilidades de contestar a un profesor?",
            "¿Quién tiene más probabilidades de convertirse en diseñador de interiores?",
            "¿Quién tiene más probabilidades de responder a un mensaje de texto tres semanas después?",
            "¿Quién tiene más probabilidades de vivir en el extranjero?",
            "¿Quién tiene más probabilidades de ser médico?",
            "¿Quién tiene más probabilidades de dar los mejores consejos?",
            "¿Quién tiene más probabilidades de crear una empresa?",
            "¿Quién tiene más probabilidades de hacerse vegano?",
            "¿Quién tiene más probabilidades de viajar al espacio?",
            "¿Quién tiene más probabilidades de mantener la calma durante una gran tormenta?",
            "¿Quién tiene más probabilidades de dejarlo todo para ayudar a un desconocido?",
            "¿Quién tiene más probabilidades de pintar una obra famosa?",
            "¿Quién tiene más probabilidades de marcharse sin despedirse?",
            "¿Quién es el más propenso a dejar caer su ordenador portátil?",
            "¿Quién tiene más probabilidades de enseñarte algo nuevo?",
            "¿Quién tiene más probabilidades de convertirse en profesor?",
            "¿Quién tiene más probabilidades de viajar por el mundo?",
            "¿Quién tiene más probabilidades de crear un podcast?",
            "¿Quién tiene más probabilidades de dar el mejor abrazo?",
            "¿Quién tiene más probabilidades de escribir una carta a mano?",
            "¿Quién tiene más probabilidades de escribir un libro?",
            "¿Quién tiene más probabilidades de planificar las vacaciones de todo el grupo?",
            "¿Quién es más propenso a empezar peleas?",
            "¿Quién es mas probable que pida perdón primero?",
            "¿Quién es mas probable que organice las salidas más divertidas?",
            "¿Quién es más proable que cuente una historia una y otra vez?",
            "¿Quién tiene más probabilidades de cancelar una salida?",
            "¿Quién tiene más probabilidades de comer del plato de otra persona?",
            "¿Quién se duerme mas temprano?",
            "¿Quien es el que siempre propone salidas?",
            "¿Quien es el psicologo del grupo?",
            "¿Quien es el que siempre falta a las juntadas?",
            "¿Quien es el que cocina mejor del grupo?"
        )
        val metQuestions: List<String> = listOf(
            "¿Eres más mental o emocional?",
            "¿Te resulta fácil aceptar ayuda para lograr tus sueños?",
            "¿Te arrepientes de no haber hecho algo en la vida?",
            "¿Qué es lo que te pone más nervioso?",
            "¿Cómo es la relación con tus padres?",
            "¿Te castigaban mucho cuando eras pequeño?",
            "¿Cuál ha sido la mejor época de tu vida? ¿Y la peor?",
            "¿Qué pesadillas te han provocado sudores más fríos?",
            "¿Cómo te describirías a ti mismo?",
            "¿Qué es lo que más valoras en una amistad?",
            "¿Cuándo fue la última vez que lloraste delante de otra persona?",
            "¿Qué significa para ti nuestra amistad?",
            "¿Cómo te gusta ser reconfortado o animado cuando estás triste o enfadado?",
            "¿Cuál es el momento de tu vida que más te puso a prueba?",
            "¿Te arrepientes de algo? Si es así, ¿de qué?",
            "Si tuvieras todo el valor posible para hacer aquello que más te asusta, ¿qué harías?",
            "¿Qué pensamientos te dificultan dormir por las noches?",
            "¿Qué es lo que más te estresa en la vida?",
            "¿Cuál es la peor decisión que has cometido?",
            "¿Cuál fue tu primera amistad? ¿Sigue en tu vida?",
            "¿Qué objeto tiene para ti mayor valor sentimental?",
            "¿Quién es la persona más importante de tu vida?",
            "¿Te resulta fácil confiar en alguien?",
            "¿Podrías perdonar a alguien que te ha sido infiel si te enteraras que de todas maneras te ama?",
            "¿Qué persona ha ejercido una influencia decisiva en ti?",
            "¿Qué cualidades valoras más en alguien?",
            "¿Qué cuatro adjetivos te dicen cómo eres?",
            "¿Qué es lo que más te gusta sobre tu persona?",
            "¿Qué es lo que te ha decepcionado más en una amistad?",
            "¿De qué estás más orgulloso en esta vida?",
            "¿De que te arrepientes?",
            "¿Preferirías tener un gran talento innato para una actividad, o la capacidad para poder esforzarte mucho?",
            "¿Te recargas estando rodeado de otras personas o pasando tiempo a solas?",
            "¿Cuál es tu plan ideal para desconectar en vacaciones?",
            "¿Cuál es tu creador de contenido preferido en TikTok? ¿Y en Instagram?",
            "¿Tienes alguna fobia?",
            "¿Cuál es tu juego de mesa preferido?",
            "¿Cuál es tu color preferido?",
            "¿Cómo es el trabajo de tus sueños?",
            "¿Cuál es la serie de tele que ves cada vez que quieres animarte?",
            "¿Desayunas lo mismo cada día o vas alternando?",
            "¿Cuál es tu película preferida de los últimos meses?",
            "¿Cuál es la serie que más has disfrutado?",
            "¿Cuál es la peor pregunta que te han hecho en una entrevista de trabajo?",
            "¿Qué es lo que siempre te hace reír?",
            "¿Eres más de mar o de montaña?",
            "¿Cuál es el viaje más largo que has realizado?",
            "¿Cuál es el emoji que más utilizas en tus chats por WhatsApp?",
            "¿Eres una persona madrugadora o una ave nocturna?",
            "¿Crees en la infinitud del Universo?",
            "¿Te gustaría conocer vida extraterrestre?",
            "¿Crees en Dios o en alguna fuerza divina?",
            "¿Te gustaría cambiar de trabajo?",
            "¿Cuál es el último libro que has leído?",
            "¿Y la última peli que has visto?",
            "¿Prefieres una discoteca o un bar tranquilo?",
            "¿Le das valor a la cultura?",
            "¿Qué museo me recomiendas visitar?",
            "¿Cuáles son tus talentos ocultos?",
            "¿Cuál es el libro que siempre quieres leer pero aún no has leído?",
            "¿Cuál ha sido tu relación más duradera?",
            "¿Prefieres pasar frío o calor?",
            "¿Cuál es la canción que te gustaría cantar en un karaoke a pleno pulmón?",
            "¿A qué país te gustaría viajar la próxima vez?",
            "¿Cómo te consideras en el sexo?",
            "¿Te cuesta ligar?",
            "¿Qué hiciste de joven que ahora no te atreverías a hacer ni de coña?",
            "¿Cambiarías tu vida por la de alguien que conoces?",
            "¿Cuál es el libro que más te ha marcado en la vida?",
            "¿Cómo cambiarías la sociedad a mejor?",
            "Si solo pudieras hacer una sola actividad para el resto de tu vida, ¿cuál sería?",
            "Si pudieras viajar hacia atrás en el tiempo para cambiar una sola cosa de tu vida, ¿cuál sería?",
            "¿Qué es para ti la normalidad?",
            "¿Qué te gustaría haber inventado?",
            "¿Te consideras más introvertido o extrovertido?",
            "¿Cuándo fue la última vez que le rompiste el corazón a alguien?",
            "¿Crees en las segundas oportunidades?",
            "¿Qué historia le contarías a un niño para que se durmiera?",
            "¿Crees que las mentiras, en según que situaciones, se pueden justificar?",
            "¿Alguna vez has sentido simpatía o has estado de acuerdo con un villano de ficción?",
            "¿Qué te gustaría aprender inmediatamente, ahora mismo, si tuvieras la oportunidad?",
            "¿Cuál es tu definición del bien y del mal?",
            "¿Cuál es la injusticia más grave que has sufrido o de la que has sido testigo?",
            "¿Cuál es la persona más agradable que has conocido?",
            "¿Qué clase de padre o madre te gustaría ser para tus futuros hijos?",
            "¿Sigues una filosofía de vida?",
            "Si pudieras cambiar el mundo, ¿qué cambiarías?",
            "¿Qué sentido tiene la vida para ti?",
            "Si pudieras acceder a una bola de cristal que sólo predice una cosa sobre tu futuro, ¿Qué te gustaría saber?",
            "¿Qué pregunta quieres que la gente te haga?",
            "Si mañana murieras, ¿qué harías hoy?",
            "¿Tienes alguna rutina que repitas cada vez que empieza el día?",
            "¿Cuáles son tus prioridades en este momento exacto de tu vida?",
            "¿Soñabas algo de pequeño que, a estas alturas, ya hayas cumplido?",
            "¿Cómo te gusta pasar tu tiempo libre?",
            "¿Qué harías mañana si ganaras hoy un millón de euros?",
            "¿Cuál fue el día más feliz de tu vida?",
            "¿Qué es lo primero que haces por la mañana?",
            "¿Qué es lo que más le sorprende a la gente de ti cuando te conoce?",
            "¿Qué es lo más emocionante de tu trabajo?",
            "¿Qué país te llama especialmente la atención?",
            "¿Qué hay en el primer puesto de tu lista de deseos?",
            "¿Cómo sería tu día perfecto?",
            "¿Qué es lo que más te gusta hacer con tus amigos?",
            "Si pudieras congelar tu vida a una edad concreta, ¿cuál sería?",
            "¿Cuál es tu mayor logro en la vida?",
            "¿Cocinas a menudo? ¿Qué te gusta cocinar?",
            "¿Te gustaría ser famoso o pasar a la historia de alguna forma?",
            "¿Qué es lo que más agradeces de esta vida?",
            "¿Cuál es tu recuerdo de la infancia más preciado?",
            "¿Qué es aquello de lo que jamás harías broma?",
            "Cuando eras pequeño, ¿qué querías ser de mayor?",
            "¿Qué aficiones quieres probar?",
            "¿Qué es lo que más te da miedo?",
            "¿Dónde ibas de vacaciones de pequeño?",
            "¿Qué es lo primero que examinas cuando estás buscando nuevo piso o casa?",
            "¿Cómo fue tu primer día en el cole?",
            "Si pudieras entrevista a alguien, ¿a quién sería?",
            "¿Qué significado tiene para ti la libertad?",
            "¿Quién es la persona más especial de tu vida?",
            "¿Cuál era tu materia favorita en el colegio?",
            "¿Cuál era la materia que menos te gustaba en el colegio?",
            "¿Qué consideras que es un buen sueldo?",
            "¿Dónde te gustaría vivir si no estuvieras en esta ciudad?",
            "¿Por qué famoso te intercambiarías durante 24 horas?",
            "¿Cuál es el amigo al que más confiarías un trabajo que implicara fuerza bruta?",
            "¿Prefieres ser experto en una sola cosa o ser simplemente bueno en todas?",
            "¿Crees en los aliens?",
            "¿Qué soñaste anoche?",
            "Si solo pudieras comer una sola cosa durante el resto de tu vida, ¿cuál sería?",
            "¿Cómo fue la peor cita que has vivido?",
            "Si pudieras vivir en otra época, ¿cuál sería?",
            "¿Cuál es tu postre preferido?",
            "¿Cuál es tu sueño más recurrente?",
            "¿Qué gran invención querrías que existiera antes de morir?",
            "¿Cuándo se puede considerar que alguien ha engañado a su pareja?",
            "¿Qué alimento o bebida nunca falta en tu nevera?",
            "Si existiera la reencarnación, ¿en qué te reencarnarías?",
            "¿Qué cambiarías de ti si pudieras volver a vivir tu vida?",
            "¿Formarías parte de los voluntarios que se irían a vivir con los extraterrestres?",
            "¿Qué frase te gustaría que pusiera en tu lápida?",
            "¿Duermes con o sin pijama?",
            "Si pudieras cenar con un personaje histórico, ¿con quién sería?",
            "¿Qué comerías en tu última cena?",
            "¿Cuál es tu chiste favorito?",
            "¿Qué comida no probarías jamás?",
            "¿Cuál es el dolor más grande que has sentido?",
            "¿Hasta qué punto te gusta u odias tu trabajo?",
            "¿Cómo vas a pasar tus próximas vacaciones?",
            "¿Cuál va a ser tu siguiente corte de pelo?",
            "¿Qué es lo que más echas de menos de tu infancia?",
            "¿Quieres tener hijos?",
            "¿Te gustaría adoptar a un niño?",
            "¿En qué país te hubiera gustado nacer?",
            "¿Qué es lo más raro que has querido ser de mayor?",
            "¿Cuál fue la primera foto que colgaste en Instagram?",
            "¿Cuál es el sitio más raro en el que te harías un tatuaje?",
            "¿Dónde te ves en 5 años? ¿Y en 10? ¿Y en 15?",
            "¿Cuál es la mayor locura que has hecho en tu vida?",
            "¿Cuál fue tu profe preferido de la infancia?",
            "¿Cómo se conocieron tus padres?",
            "De todos los miembros de tu familia, ¿con quién te llevas mejor?",
            "¿Cuál es tu afición preferida?",
            "¿Qué es lo que más te gusta de tu trabajo?",
            "¿Cuál es tu palabra preferida?",
            "¿Cuál es el mejor regalo que te han hecho? ¿Quién te lo dio?",
            "¿Alguna vez has estado en una relación sería?",
            "¿Cuál es tu palabra preferida?",
            "¿Te han roto el corazón alguna vez?",
            "¿Qué es la cosa más espontánea que has llegado a hacer?",
            "¿Cuántos años tenías cuando diste el primer beso? ¿Cómo fue?",
            "¿A quién más admiras en este mundo?",
            "¿Qué país me recomendarías para viajar?",
            "¿Qué es lo que te motiva al levantarte cada mañana?",
            "¿Cuáles son las 3 cosas que más te molestan?",
            "¿Te tatuarías el nombre de tu pareja?",
            "¿Cuál es tu plan de fin de semana ideal?",
            "¿Qué pedirías si fueran a concederte un solo deseo?",
            "¿Qué ha sido lo mejor que te ha pasado en la vida?",
            "¿Cuál es la mayor locura que has hecho por amor?",
            "¿Has sido infiel alguna vez?",
            "¿Te has enamorado de varias personas al mismo tiempo?",
            "¿Prefieres las relaciones esporádicas o duraderas?",
            "¿Te gusta hacer deporte?",
            "¿Cómo serían tus vacaciones soñadas?",
            "¿Qué es lo mejor que te ha pasado hoy?",
            "¿Qué se te da fatal?",
            "¿Qué te da miedo?",
            "¿Te gusta saber lo que está pasando en otros países?",
            "¿Qué es para ti la infidelidad?",
            "¿Cuál es tu mayor virtud y tu mayor defecto?",
            "¿Te has declarado alguna vez?",
            "¿Crees que las amistades son para siempre?",
            "¿Se puede confiar en un amigo que nunca te propone hacer planes juntos?",
            "¿Cuáles son, para ti, los tres valores más importantes?",
            "¿Cuál crees que es el adjetivo que mejor te define?",
            "¿En qué ámbito de tu vida opinas que se plasma más tu lado creativo?",
            "¿Qué es para ti el amor?",
            "¿A qué edad crees que empezaste a ser una persona madura?",
            "¿Cómo te gustaría que te recuerden cuando ya no estés?",
            "¿Consideras que tardas mucho en mostrar tus miedos y vulnerabilidades ante un amigo o una amiga?",
            "¿Quién te ha influido más en esta vida?"
        )
        val linesIdeas: List<String> = listOf("Cara sonriente",
            "Corazón",
            "Estrella",
            "Casa",
            "Árbol",
            "Pez",
            "Flor",
            "Sol",
            "Luna",
            "Montaña",
            "Gato",
            "Perro",
            "Carro",
            "Avión",
            "Barco",
            "Bicicleta",
            "Globo",
            "Pájaro",
            "Mariposa",
            "Reloj",
            "Gafas",
            "Sombrero",
            "Taza",
            "Libro",
            "Lápiz",
            "Cepillo",
            "Televisión",
            "Computadora",
            "Teléfono",
            "Lámpara",
            "Cohete",
            "Cuchara",
            "Tenedor",
            "Cama",
            "Puente",
            "Vela",
            "Galleta",
            "Huevo",
            "Pollo",
            "Loro",
            "Dinosaurio",
            "Castillo",
            "Espejo",
            "Ojo",
            "Botella",
            "Carta",
            "Micrófono",
            "Cárcel",
            "Fantasma",
            "Diamante",
            "Diente",
            "Coche de carreras",
            "Piano",
            "Batería (instrumento)",
            "Guitarra",
            "Violín",
            "Nota musical",
            "Mano",
            "Pie",
            "Chaqueta",
            "Pantalones",
            "Zapato",
            "Camisa",
            "Sombrero de copa",
            "Paraguas",
            "Lluvia",
            "Nube",
            "Relámpago",
            "Nieve",
            "Hielo",
            "Fantasma",
            "Alienígena",
            "OVNI",
            "Robot",
            "Pastel",
            "Helado",
            "Caramelo",
            "Pizza",
            "Hamburguesa",
            "Hot dog",
            "Tazón de sopa",
            "Sandwich",
            "Fruta (manzana)",
            "Vegetal (zanahoria)",
            "Medalla",
            "Copa de trofeo",
            "Bandera",
            "Escudo",
            "Espada",
            "Papiroflexia (grulla)",
            "Sombrero de chef",
            "Anillo",
            "Llave",
            "Cinta adhesiva",
            "Enchufe",
            "Cuchillo",
            "Martillo",
            "Sierra",
            "Taladro",
            "Linterna")
        val type: String = intent.extras?.getString(TYPE_KEY) ?: ""
        tvQuestion = findViewById(R.id.Question)
        cvQuestion = findViewById(R.id.cvQuestion)
        tvtitleQuestion = findViewById(R.id.titleQuestion)

        when (type) {
            WHO_KEY -> randomWhoIsQuestion(whoIsQuestions)
            DEEP_KEY -> randomDeepQuestion(deepQuestions)
            MET_KEY -> randomMetQuestion(metQuestions)
            RANDOM_KEY -> randomRandomQuestion(whoIsQuestions, deepQuestions, metQuestions)
            LINES_KEY -> randomLinesIdea(linesIdeas)
        }

        cvQuestion.setOnClickListener {
            generateQuestion(
                type,
                whoIsQuestions,
                deepQuestions,
                metQuestions,
                linesIdeas
            )
        }

    }

    private fun generateQuestion(
        type: String,
        whoIsQuestions: List<String>,
        deepQuestions: List<String>,
        metQuestions: List<String>,
        linesIdeas: List<String>
    ) {
        when (type) {
            WHO_KEY -> randomWhoIsQuestion(whoIsQuestions)
            DEEP_KEY -> randomDeepQuestion(deepQuestions)
            MET_KEY -> randomMetQuestion(metQuestions)
            RANDOM_KEY -> randomRandomQuestion(whoIsQuestions, deepQuestions, metQuestions)
            LINES_KEY -> randomLinesIdea(linesIdeas)
        }
    }

    private fun randomWhoIsQuestion(whoIsQuestions: List<String>) {
        val random = Random.nextInt(0, whoIsQuestions.size + 1)
        tvQuestion.text = whoIsQuestions[random]
        tvQuestion.setTextColor(ContextCompat.getColor(this, R.color.textlight))
        cvQuestion.setCardBackgroundColor(ContextCompat.getColor(this, R.color.block_whois))
        tvtitleQuestion.text = getString(R.string.whois)
    }

    private fun randomDeepQuestion(deepQuestions: List<String>) {
        val random = Random.nextInt(0, deepQuestions.size + 1)
        tvQuestion.text = deepQuestions[random]
        tvQuestion.setTextColor(ContextCompat.getColor(this, R.color.textdark))
        cvQuestion.setCardBackgroundColor(ContextCompat.getColor(this, R.color.block_deep))
        tvtitleQuestion.text = getString(R.string.deep)
    }

    private fun randomMetQuestion(metQuestions: List<String>) {
        val random = Random.nextInt(0, metQuestions.size + 1)
        tvQuestion.text = metQuestions[random]
        tvQuestion.setTextColor(ContextCompat.getColor(this, R.color.textlight))
        cvQuestion.setCardBackgroundColor(ContextCompat.getColor(this, R.color.block_met))
        tvtitleQuestion.text = getString(R.string.met)
    }

    private fun randomRandomQuestion(whoIsQuestions: List<String>, deepQuestions: List<String>, metQuestions: List<String>) {
        val randomList = Random.nextInt(0,3)
        when(randomList){
            0 -> {
                val random = Random.nextInt(0, whoIsQuestions.size + 1)
                tvQuestion.text = whoIsQuestions[random]
            }
            1 -> {
                val random = Random.nextInt(0, deepQuestions.size + 1)
                tvQuestion.text = deepQuestions[random]
            }
            2 -> {
                val random = Random.nextInt(0, metQuestions.size + 1)
                tvQuestion.text = metQuestions[random]
            }
        }
        tvQuestion.setTextColor(ContextCompat.getColor(this, R.color.textlight))
        cvQuestion.setCardBackgroundColor(ContextCompat.getColor(this, R.color.block_random))
        tvtitleQuestion.text = getString(R.string.random)
    }

    private fun randomLinesIdea(linesIdeas: List<String>) {
        val random = Random.nextInt(0, linesIdeas.size + 1)
        tvQuestion.text = linesIdeas[random]
        tvQuestion.setTextColor(ContextCompat.getColor(this, R.color.textdark))
        cvQuestion.setCardBackgroundColor(ContextCompat.getColor(this, R.color.block_15lines))
        tvtitleQuestion.text = getString(R.string.lines)
        tvtitleQuestion.setTextSize(TypedValue.COMPLEX_UNIT_SP, 30f)
    }
}